services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: questdb
      POSTGRES_PASSWORD: questdb
      POSTGRES_DB: questdb
    # expose locally only (remove on AWS) 34an amzaon feh goa y3rf yb2t 3la el db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questdb -d questdb"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: g1d0/questboard-web:v0.1.3
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://questdb:questdb@db:5432/questdb
      FLASK_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
