services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest
      POSTGRES_DB: questdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quest -d questdb"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data


  web:
    image: g1d0/questboard-web:v0.1.0
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://quest:quest@db:5432/questdb
      FLASK_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
