"""add password_hash

Revision ID: 02991e3dc475
Revises: c53fa5e8a68c
Create Date: 2025-09-24 19:45:52.340949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02991e3dc475'
down_revision = 'c53fa5e8a68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
